### ISSUE TITLE
KeyError: "There is no item named 'ppt/slides/NULL' in the archive"

### ISSUE THREAD

**Issue by ralmond** [ssine/pptx2md#2] opened 2020-03-03 22:39 UTC
Here is the bigger issue.  Sometimes, I'm getting a mysterious error about missing a NULL slide.  Note sure where this is from.

```
dhcp138177:Markdown ralmond$ pptx2md ../ECDQuestions1.pptx -o ECDQuestions1.md
/Users/ralmond/Library/Python/3.7/lib/python/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "/Users/ralmond/bin/pptx2md", line 8, in <module>
    sys.exit(main())
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx2md/__main__.py", line 77, in main
    prs = Presentation(file_path)
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx/api.py", line 28, in Presentation
    presentation_part = Package.open(pptx).main_document_part
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx/opc/package.py", line 125, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx/opc/pkgreader.py", line 37, in from_file
    phys_reader, pkg_srels, content_types
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx/opc/pkgreader.py", line 70, in _load_serialized_parts
    for partname, blob, srels in part_walker:
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx/opc/pkgreader.py", line 106, in _walk_phys_parts
    phys_reader, part_srels, visited_partnames
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx/opc/pkgreader.py", line 106, in _walk_phys_parts
    phys_reader, part_srels, visited_partnames
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx/opc/pkgreader.py", line 103, in _walk_phys_parts
    blob = phys_reader.blob_for(partname)
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx/opc/phys_pkg.py", line 111, in blob_for
    return self._zipf.read(pack_uri.membername)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1431, in read
    with self.open(name, "r", pwd) as fp:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1470, in open
    zinfo = self.getinfo(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1398, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'ppt/slides/NULL' in the archive"
```

I'll attach 2 slides which seem to generate this error.
[ECDQuestions1.pptx](https://github.com/ssine/pptx2md/files/4283976/ECDQuestions1.pptx)

**Comment by ssine** [comment] 2020-03-04 06:22
The error is caused by ill formated pptx file, more details at this [issue](https://github.com/scanny/python-pptx/issues/206) of dependency package python-pptx.

Since it's not resolved by python-pptx, I remove the corrupted parts in pptx file, save the purged file in [filename]_purged.pptx and proceed.

Please update pptx2md by `pip install --upgrade pptx2md` and try again.

BTW, pptx2md didn't work well on your slides as some texts are in grouped shapes, so I added the logic to ungroup them first. Looks a lot better now :)

**Comment by ssine** [comment] 2020-03-09 14:23
@ralmond Mentioning in case you didn't notice this. The issue will be closed if no further problem is spotted.

**Closed** 2020-03-18 03:15 UTC
